name: Deathmatch
main: org.rspeekenbrink.deathmatch.Deathmatch
version: 0.3
api-version: 1.13
database: true
commands:
  deathmatch:
    description: Deathmatch Commands
    usage: /deathmatch <command> <args>
    aliases: [dm]
permissions:
   deathmatch.*:
     description: Gives access to all Deathmatch commands
     default: op
     children:
       deathmatch.help.admin: true
       deathmatch.join: true
       deathmatch.join.maintenance: true
       deathmatch.leave: true
       deathmatch.place.sign: true
       deathmatch.reload: true
       deathmatch.spawn.modify: true
       deathmatch.chest.place: true
       deathmatch.chest.remove: true
       deathmatch.stats: true
       deathmatch.stats.others: true
   deathmatch.help.admin:
     description: Show admin commands
     default: op
   deathmatch.join:
     description: Allows you to join deathMatch
     default: true
   deathmatch.join.maintenance:
     description: Allows you to join the server when the server is in maintenance mode
     default: op
   deathmatch.leave:
     description: Allow you to leave deathmatch trough a command
     default: true
   deathmatch.place.sign:
     description: Allows you to place DeathMatch command signs (such as join)
     default: op
   deathmatch.reload:
     description: Allows you to reload the game config files
     default: op
   deathmatch.spawn.modify:
     description: Allows you to modify all spawns
     default: op
   deathmatch.chest.place:
     description: Allows you to place new chests
     default: op
   deathmatch.chest.remove:
     description: Allows you to remove chests
     default: op
   deathmatch.stats:
     description: Allows you to view your own stats
     default: true
   deathmatch.stats.others:
     description: Allows you to view others stats
     default: op
